# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bee212bcab8f3e1a4f2acc1c78d8529b6d7b282f1aeca6c395af57d72146963e2129fbb67409af2e45e62128d9e36f0cd4ca362444c6adcd21e78d8cd6f35050

test:
  secret_key_base: ce8a07231fe78f11b5d89498d525f0e0721eab9e6453dc7e66d3090d70a40f9eea0dee5fbdfeb26560117c51fe0b4ab55f061a8da5666082efeee827bbe4627f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
